# Generated by Django 5.1.1 on 2025-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_crud', '0003_alter_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, default='img/cliente/default.png', null=True, upload_to='img/cliente/'),
        ),
    ]
