# Generated by Django 5.1.1 on 2025-07-12 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('clientes_crud', '0004_alter_cliente_imagen'),
        ('operadores_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=4)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.administrador')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_crud.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('plastico', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('papel', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('carton', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('film', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('latas', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('palets', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('palets_cantidad', models.IntegerField(blank=True, default=0)),
                ('chatarra', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('vidrio', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('tetrapack', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/fotos/')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_crud.cliente')),
                ('idOperador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operadores_crud.operador')),
                ('idUbicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_crud.ubicacioncl')),
            ],
        ),
        migrations.CreateModel(
            name='Conforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCertificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros_crud.certificado')),
                ('idResiduo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros_crud.residuos')),
            ],
        ),
    ]
