# Generated by Django 5.1.1 on 2025-06-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuos',
            name='botellas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='chatarra',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='film',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='latas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='palets',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='palets_cantidad',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='tetrapack',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='residuos',
            name='vidrio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
