# Generated by Django 5.1.1 on 2025-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0002_residuos_botellas_residuos_chatarra_residuos_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuos',
            name='palets_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
