# Generated by Django 5.1.1 on 2025-07-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0002_alter_residuos_carton_alter_residuos_chatarra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conforma',
            name='idCertificado',
        ),
        migrations.RemoveField(
            model_name='conforma',
            name='idResiduo',
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.DeleteModel(
            name='Conforma',
        ),
    ]
