# Generated by Django 5.1.1 on 2025-07-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('clientes_crud', '0004_alter_cliente_imagen'),
        ('registros_crud', '0003_remove_conforma_idcertificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField()),
                ('tipoCertificado', models.CharField(max_length=5)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.administrador')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_crud.cliente')),
            ],
        ),
    ]
