# Generated by Django 5.1.1 on 2025-07-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0003_alter_residuos_palets_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residuos',
            name='botellas',
        ),
    ]
