# Generated by Django 5.2.5 on 2025-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0004_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuos',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
