# Generated by Django 5.1.1 on 2025-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0004_remove_residuos_botellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/fotos/'),
        ),
    ]
