# Generated by Django 5.1.1 on 2025-09-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_crud', '0005_residuos_fechacreacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residuos',
            name='foto',
        ),
        migrations.CreateModel(
            name='ResiduosFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='registros_crud.residuos')),
            ],
        ),
    ]
